version: '3'
services:
  mysql_db:
    hostname: public-tax-management-db
    container_name: public-tax-management
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: public-tax-management-db
      MYSQL_USER: public-tax-management
      MYSQL_PASSWORD: public-tax-management
      MYSQL_ROOT_PASSWORD: public-tax-management
    logging:
      driver: "json-file"
      options:
        max-size: 500m